#ifndef __ECTF_PARAMS__
#define __ECTF_PARAMS__
#define COMPONENT_ID 286331172
#define COMPONENT_BOOT_MSG "Component boot"
#define ATTESTATION_LOC "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
#define ATTESTATION_DATE "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
#define ATTESTATION_CUSTOMER "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
#endif
